# Generated by Django 5.2.7 on 2026-01-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
