# Generated by Django 5.2.7 on 2026-01-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_remove_post_saved_by_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
